### ISSUE TITLE
Missing Python3 module twelvedata

### ISSUE THREAD

**Issue by Phozer** [veebch/bullion#1]
First of all, great Project!

I believe that the Phyton3 module installation of `twelvedata` is missing in the instructions for installing. 

My python script failed to execute  because of the missing module. 

Installed with:
`python3 -m pip install twelvedata`

Or maybe add it to the [requirements.txt](https://github.com/veebch/bullion/blob/main/requirements.txt).

**Comment by veebch** [comment]
Thanks! Added to requirements.txt
